=== MERQ-Systems/momonahealthcare_webapp/formtools/modules/form_builder/schemas/template_set-1.0.0.json
{
  "title": "Template Set Schemas",
  "schema_version": "1.0.0",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "schema_version": {
      "type": "string",
      "oneOf": [
        {
          "type": "string",
          "enum": ["1.0.0"]
        }
      ]
    },
    "template_set_name": {
      "type": "string"
    },
    "template_set_version": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "last_updated": {
      "type": "string"
    },
    "templates": {
      "type": "object",
      "properties": {
        "page_layout": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/template"
          }
        },
        "header": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/template"
          }
        },
        "footer": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/template"
          }
        },
        "form_page": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/template"
          }
        },
        "review_page": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/template"
          }
        },
        "thankyou_page": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/template"
          }
        },
        "form_offline_page": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/template"
          }
        },
        "continue_block": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/template"
          }
        },
        "navigation": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/template"
          }
        },
        "error_message": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/template"
          }
        }
      },
      "required": [
        "page_layout",
        "header",
        "footer",
        "form_page",
        "review_page",
        "thankyou_page",
        "form_offline_page",
        "continue_block",
        "navigation",
        "error_message"
      ]
    },

    "resources": {
      "type": "object",
      "properties": {
        "css": {
          "type": "array"
        },
        "js": {
          "type": "array"
        }
      }
    },
    "placeholders": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "placeholder_label": {
            "type": "string"
          },
          "placeholder": {
            "type": "string"
          },
          "field_type": {
            "type": "string",
            "enum": ["textbox", "textarea", "radios", "checkboxes", "select", "multi-select"]
          },
          "field_orientation": {
            "type": "string",
            "enum": ["na", "horizontal", "vertical"]
          },
          "default_value": {
            "type": "string"
          },
          "options": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "option_text": {
                  "type": "string"
                }
              }
            }
          }
        },
        "required": [
          "placeholder_label",
          "placeholder",
          "field_type",
          "field_orientation",
          "default_value"
        ]
      }
    }
  },
  "definitions": {
    "template": {
      "type": "object",
      "properties": {
        "template_name": {
          "type": "string"
        },
        "content": {
          "type": "string"
        }
      },
      "required": [
        "template_name",
        "content"
      ]
    }
  },
  "required": [
    "schema_version",
    "template_set_name",
    "template_set_version",
    "description",
    "last_updated",
    "templates"
  ]
}

=== MERQ-Systems/momonahealthcare_webapp/formtools/modules/form_builder/default_template_sets/default-1.2.json
{
  "schema_version": "1.0.0",
  "template_set_name": "Default Template Set",
  "template_set_version": "1.2",
  "description": "A neutral, grey-themed set of templates that lets you choose a highlight colour to match your site.",
  "last_updated": "2018-02-04 16:45:00",
  "templates": {
    "page_layout": [
      {
        "template_name": "Page Layout",
        "content": "{{header}}\n{{page}}\n{{footer}}"
      }
    ],
    "header": [
      {
        "template_name": "Header",
        "content": "<!DOCTYPE html>\n<html>\n<head>\n<title>{{$form_name}}</title>\n  {{$required_resources}}\n  {{$R.styles}}\n</head>\n<body>\n<div class=\"ts_page\" style=\"width:900px\">\n  <div class=\"ts_header\">\n    <h1>{{$form_name}}</h1>\n  </div>\n  <div class=\"ts_content\">\n    <div class=\"ts_content_inner\">"
      },
      {
        "template_name": "No Header",
        "content": "<!DOCTYPE html>\n<html>\n<head>\n<title>{{$form_name}}</title>\n  {{$required_resources}}\n  {{$R.styles}}\n</head>\n<body>\n<div class=\"ts_page\" style=\"width:900px\">\n  <div class=\"ts_content\">\n    <div class=\"ts_content_inner\">"
      }
    ],
    "footer": [
      {
        "template_name": "Footer",
        "content": "    </div>\n  </div>\n</div>\n\n</body>\n</html>"
      }
    ],
    "form_page": [
      {
        "template_name": "Form Page",
        "content": "{{navigation}}\n\n<h2>{{$page_name}}</h2>\n\n{{error_message}}\n\n<form action=\"{{$page_url}}\" method=\"post\" enctype=\"multipart/form-data\"\n  id=\"ts_form_element_id\" name=\"edit_submission_form\">\n  <input type=\"hidden\" id=\"form_tools_published_form_id\" value=\"{{$published_form_id}}\" />\n{{foreach from=$grouped_fields key=k item=curr_group name=row}}\n  {{assign var=group value=$curr_group.group}}\n  {{assign var=fields value=$curr_group.fields}}\n\n    <a name=\"s{{$group.group_id}}\"></a>\n  {{if $group.group_name}}\n    <h3>{{$group.group_name}}</h3>\n  {{else}}\n    <br />\n  {{/if}}\n\n  {{if $fields|@count > 0}}\n  <table class=\"table_1\" cellpadding=\"1\" cellspacing=\"1\" border=\"0\" width=\"798\">\n  {{/if}}\n    \n  {{foreach from=$fields item=curr_field}}\n    {{assign var=field_id value=$curr_field.field_id}}\n    <tr>\n      <td width=\"180\" valign=\"top\">\n        {{$curr_field.field_title}}\n        <span class=\"req\">{{if $curr_field.is_required}}*{{/if}}</span>\n      </td>\n      <td class=\"answer\" valign=\"top\">\n        <div class=\"pad_left\">\n        {{edit_custom_field form_id=$form_id field_info=$curr_field field_types=$field_types\n          settings=$settings submission_id=$submission_id}}\n        </div>\n      </td>\n    </tr>\n  {{/foreach}}\n\n  {{if $fields|@count > 0}}\n    </table>  \n  {{/if}}\n\n{{/foreach}}\n\n{{continue_block}}\n\n</form>"
      }
    ],
    "review_page": [
      {
        "template_name": "Review Page",
        "content": "{{navigation}}\n\n<h2>{{$review_page_title}}</h2>\n\n<form action=\"{{$page_url}}\" method=\"post\" enctype=\"multipart/form-data\">\n{{foreach from=$grouped_fields item=curr_group}}\n  {{assign var=group value=$curr_group.group}}\n  {{assign var=fields value=$curr_group.fields}}\n\n  {{if $fields|@count > 0}}\n    <h3>\n      <a href=\"?page={{$group.custom_data}}#s{{$group.group_id}}\">EDIT</a>\n      {{$group.group_name}}\n    </h3>\n  \n    <table class=\"table_1\" cellpadding=\"1\" cellspacing=\"1\" border=\"0\" width=\"798\">\n  {{/if}}\n\n  {{foreach from=$fields item=curr_field}}\n    {{assign var=field_id value=$curr_field.field_id}}\n    <tr>\n      <td width=\"200\" class=\"pad_left_small\" valign=\"top\">{{$curr_field.field_title}}</td>\n      <td class=\"answer\" valign=\"top\">\n        <div class=\"pad_left\">\n        {{edit_custom_field form_id=$form_id submission_id=$submission_id\n          field_info=$curr_field field_types=$field_types settings=$settings}}\n        </div>\n      </td>\n    </tr>\n  {{/foreach}}\n\n  {{if $fields|@count > 0}}\n    </table>    \n  {{/if}}\n{{/foreach}}\n\n{{continue_block}}\n\n</form>\n"
      }
    ],
    "thankyou_page": [
      {
        "template_name": "Thankyou Page",
        "content": "{{navigation}}\n\n{{$thankyou_page_content}}"
      }
    ],
    "form_offline_page": [
      {
        "template_name": "Form Offline Page",
        "content": "{{$form_offline_page_content}}"
      }
    ],
    "continue_block": [
      {
        "template_name": "Continue - Button Only",
        "content": "<div class=\"ts_continue_button\">\n  <input type=\"submit\" name=\"form_tools_continue\" value=\"Continue\" />\n</div>"
      },
      {
        "template_name": "Continue - Detailed",
        "content": "<div class=\"ts_continue_block\">\n  <input type=\"submit\" name=\"form_tools_continue\" value=\"Continue\" />\n  This is page <b>{{$current_page}}</b> of <b>{{$num_pages}}</b>. You must complete \n  all steps in order for your submission to be processed. Please click continue.\n</div>\n\n"
      }
    ],
    "navigation": [
      {
        "template_name": "Navigation",
        "content": "<ul id=\"css_nav\" class=\"nav_{{$nav_pages|@count}}_pages\">\n  {{foreach from=$nav_pages item=page_info name=row}}\n    {{assign var=i value=$smarty.foreach.row.iteration}}\n    {{if $current_page > $i && $current_page != $num_pages}}\n      <li><a href=\"?page={{$i}}\">{{$page_info.page_name}}</a></li>\n    {{elseif $current_page == $i || $current_page == $num_pages}}\n      <li class=\"css_nav_current_page\">{{$page_info.page_name}}</li>\n    {{else}}\n      <li>{{$page_info.page_name}}</li>\n    {{/if}}\n  {{/foreach}}\n</ul>"
      },
      {
        "template_name": "Navigation - Numbered",
        "content": "<ul id=\"css_nav\" class=\"nav_{{$nav_pages|@count}}_pages\">\n  {{foreach from=$nav_pages item=page_info name=row}}\n    {{assign var=i value=$smarty.foreach.row.iteration}}\n    {{if $current_page > $i && $current_page != $num_pages}}\n      <li><a href=\"{{$filename}}?page={{$i}}\">{{$i}}. {{$page_info.page_name}}</a></li>\n    {{elseif $current_page == $i || $current_page == $num_pages}}\n      <li class=\"css_nav_current_page\">{{$i}}. {{$page_info.page_name}}</li>\n    {{else}}\n      <li>{{$i}}. {{$page_info.page_name}}</li>\n    {{/if}}\n  {{/foreach}}\n</ul>"
      },
      {
        "template_name": "No Navigation",
        "content": ""
      }
    ],
    "error_message": [
      {
        "template_name": "Error Message",
        "content": "{{if $validation_error}}\n  <div class=\"fb_error\">{{$validation_error}}</div>\n{{/if}}"
      }
    ]
  },
  "resources": {
    "css": [
      {
        "resource_name": "General Styles",
        "placeholder": "styles",
